[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags =
    -std=gnu++17
    -DRF_CC1101=1
    -DRF_MODULE_FREQUENCY=433.92
    -DRSSI_THRESHOLD=-82
    -DRF_DEBUG=0
    ; CC1101 SPI pins (см. PINOUT.md)
    -DRF_MODULE_CS=5
    -DRF_MODULE_GDO0=4
    -DRF_MODULE_GDO2=2
build_unflags = -std=gnu++11
lib_deps =
    knolleary/PubSubClient@^2.8
    bblanchon/ArduinoJson@^7.0
    https://github.com/NorthernMan54/rtl_433_ESP.git
