[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    knolleary/PubSubClient@^2.8
    paulstoffregen/OneWire@^2.3
    milesburton/DallasTemperature@^3.11
    adafruit/DHT sensor library@^1.4
    adafruit/Adafruit Unified Sensor@^1.1
    bblanchon/ArduinoJson@^7.0
